### PR TITLE
random fixes

### PR DESCRIPTION
**Pull request by zimbatm**

### CODE REVIEW

**Comment by elitak** [comment]
Looks good; thanks.

**Comment by fiksn** [comment]
Conceptually it is good, but I have a problem with it in practice - generated nameservers are (at least in my case) without quotes like 1.1.1.1 not "1.1.1.1". And thus it fails with: 
```
error: The option value `networking.nameservers.[definition 1-entry 1]' in `/etc/nixos/networking.nix' is not of type `string'.
```

**Comment by elitak** [comment]
I made a change to fix that. Can you try the latest commit?

**Comment by fiksn** [comment]
Thanks, this works - I get something like:
```
 nameservers = [ "127.0.0.53"
 ];
``` 
(mind the extra new-line). So I guess the bug is fixed, but I still have issues - it seems this comes from systemd-resolved (original was a Ubuntu 20.04 instance). I will try some `sed` before doing nixos-infect. It would be great if you could manually override the value through some environment variable tho.

**Comment by elitak** [comment]
The entire 127.0.0.0/8 network is loopback... I don't understand why your system would use that address, unless there is a DNS caching service running locally on port 53, whose configuration incorporates a remote DNS server to pass requests to.

You can customize any part of the config, but it's not very convenient, e.g.:
```
mkdir -p /etc/nixos
echo '{ lib, ... }: { networking.nameservers = lib.mkForce [ "8.8.8.8" ]; }' > /etc/nixos/custom.nix
NIXOS_IMPORT=/etc/nixos/custom.nix ./nixos-infect
```
The `$NIXOS_IMPORT` value is put into the main `imports = [ ];` block.

**Comment by zimbatm** [comment]
Sorry for causing all these troubles.

It's possible that some systems come pre-configured with dnsmask or some other sort of local resolver daemon. On Debian, the package install automatically replaces /etc/resolv.conf with `nameserver 127.0.0.1` when that package gets installed.

@fiksn what ISP/Distro combo are you using?

**Comment by fiksn** [comment]
Well I am a mostly a Debian/MacOS user. I also have a test workstation w/ NixOS. The current use case was converting a DigitalOcean droplet w/ Ubuntu 20.04 to NixOS 20.09. It seems that those machines come with `systemd-resolved` installed by default which listens on loopback interface.  What I did now is just: 
```
- sed -i 's/127.0.0.53/8.8.8.8/g' /etc/resolv.conf
``` 
in cloud-config before calling nixos-infect. But the NIXOS_IMPORT override mechanism might actually be much more "in the Nix spirit". Thanks for that.

**Comment by DavHau** [comment]
I think it would be best to just put 8.8.8.8 back in there.
This works basically on every cloud provider. It is the most stable setting we can have as a default.

**Comment by fiksn** [comment]
Well some providers might do egress filtering and 8.8.8.8 will not work. I think the reasoning that if it worked before it should also after `nixos-infect` is sane. The only exception is if it worked _just_ because the server had a local nameserver installed before (one or the other way). Thus if nameserver IP is in 127.0.0.0/8 or some local IP, then falling back to 8.8.8.8 might make sense to improve UX.

**Comment by supermarin** [comment]
So I just got here after going down the rabbit hole of setting up a DigitalOcean nixos node.
Seems like their Ubuntu 20.04 uses `systemd-resolve` and completely breaks nixos installation's DNS as soon as nixos-rebuild is done. I think as a temporary fix this should be reverted and either 8.8.8.8 or Cloudflare's 1.1.1.1 should be put in place. As a proper fix, probably detecting DO and mimicking their behavior with a local relay?

**Comment by elitak** [comment]
Please try the commit I just pushed. It simply replaces any entries of "127.*" or "::1" with "8.8.8.8".

**Comment by supermarin** [comment]
@elitak sorry for delay, I'm not able to test this anytime soon (maybe next week). Looking at your commit the fix looks good.
Will report back here only if I find issues with the next deployment.

**Pull request merged**
