### PR TITLE
Add support for Oracle Cloud Infrastructure

### PR DESCRIPTION
**Pull request by ilian**
- Add EFI support (required for AArch64 instances on OCI)
- Support non-ext4 root file systems (Oracle Linux images use XFS)

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Tested this on Ubuntu 20.04 on one of their VM.Standard.A1.Flex instances and it seems to have worked!

**Comment by lf-** [comment]
Tested on Oracle Linux 7.9, works for me too.

**Comment by elitak** [comment]
Thanks.

**Comment by eljojo** [comment]
🙌 thanks!!!

**Pull request merged**
